// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgTCIU0XpXXoHliTsChIK2fJmgsvNlwk',
    appId: '1:625886238811:web:8898900279450d695b477e',
    messagingSenderId: '625886238811',
    projectId: 'qldl-2b875',
    authDomain: 'qldl-2b875.firebaseapp.com',
    storageBucket: 'qldl-2b875.firebasestorage.app',
    measurementId: 'G-09NT1YJ3BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPnmy3pasEoRXV7LtH6rpCnIUWixHjl8',
    appId: '1:625886238811:android:83ad8476b8de59565b477e',
    messagingSenderId: '625886238811',
    projectId: 'qldl-2b875',
    storageBucket: 'qldl-2b875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl1Tn3iHGHMMWzGP2zIw_owkgid8UTZIU',
    appId: '1:625886238811:ios:370e964beae5cd745b477e',
    messagingSenderId: '625886238811',
    projectId: 'qldl-2b875',
    storageBucket: 'qldl-2b875.firebasestorage.app',
    iosBundleId: 'com.example.cuoiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl1Tn3iHGHMMWzGP2zIw_owkgid8UTZIU',
    appId: '1:625886238811:ios:370e964beae5cd745b477e',
    messagingSenderId: '625886238811',
    projectId: 'qldl-2b875',
    storageBucket: 'qldl-2b875.firebasestorage.app',
    iosBundleId: 'com.example.cuoiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWgTCIU0XpXXoHliTsChIK2fJmgsvNlwk',
    appId: '1:625886238811:web:c38bf4030fd71fba5b477e',
    messagingSenderId: '625886238811',
    projectId: 'qldl-2b875',
    authDomain: 'qldl-2b875.firebaseapp.com',
    storageBucket: 'qldl-2b875.firebasestorage.app',
    measurementId: 'G-8RFEPQTTNS',
  );

}